sudo: required
services: 
    - docker

before_install:
    - docker build -t adrianoxy/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true adrianoxy/react-test npm test

after_success:
    - docker build -t adrianoxy/multi-client ./client
    - docker build -t adrianoxy/multi-nginx ./nginx
    - docker build -t adrianoxy/multi-server ./server
    - docker build -t adrianoxy/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push adrianoxy/multi-client
    - docker push adrianoxy/multi-nginx 
    - docker push adrianoxy/multi-server 
    - docker push adrianoxy/multi-worker
